### ISSUE TITLE
TV版Youtube无法观看

### ISSUE THREAD

**Issue by doudoumiao** [fengixng/google-hosts#10]
在路由器里部署了Dnsmasq，局域网里都能顺畅观看Youtube了，非常感谢。看到电视盒子就想也装个Youtube TV版试试，结果App打开一片空白，不知是什么原因

**Comment by fengixng** [comment]
我用手机测试youtube TV版正常，你看你的盒子使用的DNS服务器是不是更改过而不是默认分配的路由器DNS

**Comment by KalelCooper** [comment]
我这只有刷了cm网站上rom的手机能用youtube，其它的大陆产的手机和电视盒都不能用youtube
