### ISSUE TITLE
这个dnsmasq.conf怎么在安卓中使用

### ISSUE THREAD

**Issue by lpdswing** [fengixng/google-hosts#2]
我网上搜索了很多教程都没弄好，怎么才能让手机能在谷歌商店下载应用，

**Comment by fengixng** [comment]
dnsmasq还是在路由器上使用起来更好，安卓上使用起来太麻烦

**Comment by lpdswing** [comment]
我知道路由器好弄，一个是路由器不支持，安卓教程就那么2个 还写得很含糊

**Comment by fengixng** [comment]
http://www.blogbus.com/chenshaoju-logs/164690776.html
你试下按这个教程弄吧，不过我不知道能不能用，因为我是在路由器是上配置的

**Comment by iiipengyingjun** [comment]
在路由器上怎么使用？ 有教程吗？

**Comment by fengixng** [comment]
替换路由器文件，/etc下的dnsmasq.conf文件，并且把dnsmasq.hosts也给放进去。

**Comment by doudoumiao** [comment]
很棒，特意注册账号上来感谢一下
