### ISSUE TITLE
为什么要换成219.76.4.3啊

### ISSUE THREAD

**Issue by KalelCooper** [fengixng/google-hosts#20]
这个不是直联的IP, 是第三方做的透明代理， 最好是只把 googlevideo.com 指向这个地址吧， 我使用的是 dnsmasq

**Comment by fengixng** [comment]
使用GGC虽然好，但是不同地区会有不同的封禁，上一个版本我填的是澳门的GGC，但是依然有很多人反映用不了，虽然我测试我本地正常，全国只有小部分地区不能使用，但是在不同时间段也会有其他的区域无法使用。
但是这个香港移动的sni proxy在没谁都用不了，在没就都能正常使用。
对于绝大数人再说，使用GGC的IP和使用sni proxy的风险是一样大的，对于注重自身安全的人来说，也不会使用别人提供的HOSTS和dnsmasq配置文件
再说这个本身只是我自用的而已，发到github了。对于我自身来说，虽然我也有其他辅助翻墙的手段，但是这种是我认为最方便的

**Comment by KalelCooper** [comment]
感谢你的付出。另外这个sni proxy好像不能用facebook了

**Comment by KalelCooper** [comment]
还有wiki的也打不开, 证书也成google的了
