### ISSUE TITLE
某些u2b视频不能用win+chrome播放, 但用软件youtube-dl可下载该视频

### ISSUE THREAD

**Issue by KalelCooper** [fengixng/google-hosts#22]
https://www.youtube.com/watch?v=sCTQr9f4-jM
详细信息里面那个 Stream Host: 后面是空的.
其他视频没有问题, 以前遇到过这种情况, 这个视频可能过一阵子又能播放了. 用的 dnsmasq.conf
谢谢

**Comment by KalelCooper** [comment]
现在这个视频能播放了。感觉是某个环节需要缓存完才行。

**Comment by fengixng** [comment]
好像是某些有些地址这个服务器不转发，会404，有些能播放，暂时没解决的办法
