### ISSUE TITLE
你好！请问下梅林固件要怎么正确使用dnsmasq.conf 文件？

### ISSUE THREAD

**Issue by hexianfu** [fengixng/google-hosts#24]
我用telnet连上去 粘贴你的内容，重启路由，然后连国内的都上不了。梅林shadowsocks插件里的dns也可以设置dnsmasq 直接粘贴进去就行，效果一样 粘贴完 国内的都上不去。能不能告诉下该怎么弄这个。谢谢你！

**Comment by fengixng** [comment]
如果装的有chinadns，不适用chinadns的远程解析试试

**Comment by hexianfu** [comment]
试过在 /jffs/configs/dnsmasq.d 放置一个 dnsmasq.conf 配置文件 这个不行 也试过在 /jffs/configs 下放置也不行！ 放置之后重启路由连国内的都上不了了！

**Comment by hexianfu** [comment]
已经解决了
