### ISSUE TITLE
能解释一下 dnsmasq.hosts 的作用么

### ISSUE THREAD

**Issue by KalelCooper** [fengixng/google-hosts#29]
多谢

**Comment by fengixng** [comment]
google的ns服务器指向正确的地址

**Comment by KalelCooper** [comment]
不好意思这么晚才来回复。
它的作用是用于递归服务器么，是递归查询google.com youtube.com这些域名时最后要去查询的服务器么?
自建递归dns服务器的时候不是已经能防止污染了么?  这里指定google的ns的ip具体是为了什么目的呢? 希望能多指点一些, 十分感谢.

**Comment by fengixng** [comment]
实际上一般人正常使用是否正确指定是不会有任何影响的，只不过是因为我之前使用ns服务器查找GGC IP,而进行正确的指向。

**Comment by KalelCooper** [comment]
多谢了
