### ISSUE TITLE
应当使用同一个IP 访问 googlevideo.com 和 youtube.com 等域名

### ISSUE THREAD

**Issue by KalelCooper** [fengixng/google-hosts#38]
确切的说是访问如下域名的时候应当使用同一个IP，不然访问 googlevideo.com 的时候会出现很多 403 错误，应当是服务端做了限制。
gvt1.com
googlevideo.com
ytimg.com
youtu.be
youtube.com
youtube-nocookie.com

现在的 dnsmasq.conf 中 gvt1.com googlevideo.com 使用了 sniproxy，但其域名直接使用了google的ip，这样就会造成很多403错误。

另外 219.76.4.x 段的 sni 都阵亡了。大佬能否直接提供sni的获取方式呢， 非443端口的也行啊，可以用iptables转发。 多谢了

**Comment by fengixng** [comment]
403错误应该是google的服务器限制的，目前这种情况还是能用播放，所以我就没全局使用sni了。
但是不能播放youtube的直播，我估计是因为直连和sni同时使用的原因。我一会测试下像之前全局使用sni看能不能播放吧。
219.76.4.0/24看样子确实是全都挂了，我换个新的SNI。
扫描sni可以使用@johnsonz的go-sni-detector。

**Comment by fengixng** [comment]
目前如果更换sni又要添加一大波的域名了，我的慢慢添加，估计得一段时间hosts才能更新

**Comment by fengixng** [comment]
已经修复好了，你可以试下最新版本。

**Comment by KalelCooper** [comment]
多谢，已经可以了。这个速度还行

**Comment by KalelCooper** [comment]
dnsmasq.conf 的 address=/<name>/<ip> 这样的配置，可以替代所有子域名了。这样 facebook 那一堆记录可以精简很多的。

**Comment by fengixng** [comment]
主要是有些子域名的IP是不一样的，我懒得整理了............
