### ISSUE TITLE
大佬 冷不冷多公布几个sni呢

### ISSUE THREAD

**Issue by KalelCooper** [fengixng/google-hosts#42]
现在这个速度还可以接受，但比不上之前个网段的爽，之前那个网段的看油管直接显示上万 Kbps。
还有现在这个到东八区晚上就不行了，勉强能看240P的视频。

如果有的话可以备注在配置文件里面， 可以根据需要自行选择了。 没有就算了。

多谢。

**Comment by fengixng** [comment]
自己慢慢扫吧，这玩意公布出来死的太快，毕竟人家的服务器资源也是有限的

**Comment by KalelCooper** [comment]
好吧
