### ISSUE TITLE
这几天开始不能流畅的看YouTube了只有我吗...

### ISSUE THREAD

**Issue by OldYogurt** [fengixng/google-hosts#6]

**Comment by fengixng** [comment]
我使用正常

**Comment by hexianfu** [comment]
@fengixng  兄弟你环聊把我屏蔽了吗，我用9月5号环聊过你。如果打扰到你不好意思哦

**Comment by fengixng** [comment]
@hexianfu 没看到抱歉

**Comment by chuanzhongliu** [comment]
看YouTube没问题吧

**Comment by CHN008** [comment]
这两天是会出现播放过程中中断,提示发生错误,刷新一下又好了,过段时间可能又会出现.

**Comment by chuanzhongliu** [comment]
我的一直转圈，根本不能看

CHN008 <notifications@github.com>于2016年9月16日周五 12:50写道：

**Comment by fengixng** [comment]
如果使用的是hosts的话，使用不完美是很正常的，因为googlevideo的地址太多，我只添加的中国经常解析的到的地址，如果不是我添加的那些地址，那么就会转圈或者播放出现问题
